name: Bug Report
description: Create a bug report to help us find and fix bugs!
title: "[Bug]: "
labels: [bug, needs triage]
body:
- type: checkboxes
  attributes:
    label: Before Reporting
    description: "I have double checked and agree with the following:"
    options:
    - label: I found no existing issues matching my bug
      required: true
    - label: My issue is not caused by a theme
      required: true
    - label: My issue is not caused by a plugin
      required: true
- type: dropdown
  attributes:
    label: Bug Category
    description: What type of bug is this?
    options:
      - Aesthetic/UI Bug (Something isn't looking quite right)
      - Functional Bug (Something isn't working as expected)
      - Documentation Bug (Something isn't clear or correct in the documentation)
      - Security Bug (Something is broken that could lead to a security vulnerability)
      - Performance Bug (Something is slowing down or not working as expected)
      - Other Bug (Something that doesn't fall under the above)
    validations:
      required: true
- type: textarea
  attributes:
    label: Describe the Bug
    description: A clear and concise description of what you're experiencing. If applicable, add screenshots to help explain your problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: dropdown
  attributes:
    label: Operating System
    options:
      - Windows
      - Linux
  validations:
    required: true
- type: input
  attributes:
    label: Version
    description: What version of Millennium are you running?
    placeholder: v0.x.x
    validations:
      required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
